-- Execute este script no SQL Editor do Supabase.
create table if not exists public.solicitacoes_ferias (
  id bigint generated by default as identity primary key,
  colaborador_id uuid not null references public.usuario(id) on delete cascade,
  tipo text not null check (tipo in ('periodo', 'fixos')),
  data_inicio date,
  data_fim date,
  quantidade_dias integer not null check (quantidade_dias > 0 and quantidade_dias <= 30),
  observacoes text,
  status text not null default 'Pendente' check (status in ('Pendente', 'Aprovada', 'Recusada')),
  observacao_admin text,
  decidido_por uuid references public.usuario(id),
  decidido_em timestamptz,
  created_at timestamptz not null default now(),
  constraint periodo_datas_validas check (
    (tipo = 'fixos' and data_inicio is null and data_fim is null)
    or
    (tipo = 'periodo' and data_inicio is not null and data_fim is not null and data_fim >= data_inicio)
  )
);

create index if not exists solicitacoes_ferias_colaborador_idx
  on public.solicitacoes_ferias (colaborador_id);

create index if not exists solicitacoes_ferias_status_idx
  on public.solicitacoes_ferias (status);

alter table public.solicitacoes_ferias enable row level security;

-- O backend usa a service_role para validar permissões. Estas políticas
-- também protegem acessos diretos feitos com a chave pública.
create policy "colaborador consulta suas ferias"
  on public.solicitacoes_ferias for select
  using (auth.uid() = colaborador_id);

create policy "colaborador cria suas ferias"
  on public.solicitacoes_ferias for insert
  with check (auth.uid() = colaborador_id);
